### ISSUE TITLE
bug错误： heroku搭建dandan节点失效

### ISSUE THREAD

**Issue by Root-1404** [LussacZheng/dandanplay-resource-service#4]
dan1404.herokuapp.com
页面可预览，链接填入失效

[dan1404-logs-1666772182384.txt](https://github.com/LussacZheng/dandanplay-resource-service/files/9867508/dan1404-logs-1666772182384.txt)

**Comment by LussacZheng** [comment]
其实已经部署好了，只是 `herokuapp.com` 可能被墙了，你试试挂上代理，是能正常访问的。

另外 Heroku 从2022年11月28日开始就[不再免费](https://blog.heroku.com/next-chapter)了，目前还是建议

- 使用 自己的域名+Cloudflare Worker 部署
- 或直接使用其他人部署好的节点

之后我可能会将 Heroku 相关内容从项目文档中移除。

**Comment by LussacZheng** [comment]
Close since Heroku is [no longer free](https://web.archive.org/web/20221125153310/https://blog.heroku.com/next-chapter). Related code has been removed in commit e10575c69e6d3e93274247308e021310778c6916.
