### ISSUE TITLE
请求出错，求大佬更新下代码

### ISSUE THREAD

**Issue by ACGAPI** [LussacZheng/dandanplay-resource-service#7]
网页可以打开，但是请求出错。同样的代码版本 https://k.dandanplay.workers.dev 该地址测试通过。我部署的不行，应该是代码改变了，由于我是代码小白，不知道怎么调。求大佬更新一下
![1](https://github.com/LussacZheng/dandanplay-resource-service/assets/87590718/7e39c58c-5c59-4588-be33-4be478cbcc84)
![2](https://github.com/LussacZheng/dandanplay-resource-service/assets/87590718/25539797-218f-424d-8be4-69c8bae480d8)

**Comment by LussacZheng** [comment]
1. `*.workers.dev` 使用的是基于 Cloudflare Workers 的版本，而你使用的是基于 Golang 的版本。
2. 我在本地测试了一下 Golang 版本，我这边没有问题。
3. 你是在 自己电脑上 还是 云服务器上 部署的？如果是在自己电脑上，那么你能通过浏览器正常访问 "https://share.dmhy.org/topics/list/page/1?keyword=&sort_id=0&team_id=0&order=date-desc" 这个网址吗？

**Comment by ACGAPI** [comment]
> 1. `*.workers.dev` 使用的是基于 Cloudflare Workers 的版本，而你使用的是基于 Golang 的版本。
> 2. 我在本地测试了一下 Golang 版本，我这边没有问题。
> 3. 你是在 自己电脑上 还是 云服务器上 部署的？如果是在自己电脑上，那么你能通过浏览器正常访问 "https://share.dmhy.org/topics/list/page/1?keyword=&sort_id=0&team_id=0&order=date-desc" 这个网址吗？


1.大佬打扰了，不好意思，该问题今天自行恢复了，现在正常了。
2.我是同时在云服务器和Cloudflare Workers都部署了该项目，昨天晚上两个版本都处于提出的异常状态，而且CFW版本的0.0.4和0.0.5版本都进行了删除项目重新部署，但都没有效果。
3.由于一直使用的都是云服务器部署的版本，当云服务器和 Cloudflare Workers 都出现该问题，而其它热心人士部署的检测正常，我以为是代码需要进行更新。

**Comment by LussacZheng** [comment]
可能是近期 dmhy 本身服务器的问题，就在刚才，我用浏览器都无法正常访问 https://share.dmhy.org/ 网站。
